version: '3.8'

services:
  php-fpm:
    container_name: php-container
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - SYMFONY_VERSION=${SYMFONY_VERSION}
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../src/:/var/www

  db:
    container_name: database-container
    image: postgres:12
    restart: always
    environment:
        POSTGRES_PASSWORD: cachorropwd
        POSTGRES_DB: cachorro
    ports:
        - 5432:5432
    volumes:
        - ./data/postgres:/var/lib/postgresql/data


  nginx:
    container_name: server-container
    build:
      context: ./nginx
    volumes:
      - ./../src/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
