version: '3.8'

services:
  php-fpm:
    container_name: php-container
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - SYMFONY_VERSION=${SYMFONY_VERSION}
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../src/:/var/www